### ISSUE TITLE
Number of filters in ResBlock different from paper

### ISSUE THREAD

**Issue by Screeen** [JiuSenso/SELD-TCN#5]
Hi, thank you for sharing your code.
I noticed that you use 128 filters in the second temporal convolutional layers, instead of 256 as in the original publication.

Why is that?

Cheers, Gio

**Comment by giusenso** [comment]
I implemented several variants of this network, at the end I just uploaded one of them. It was a long time ago, but I guess I did it in order to speed up the training a little bit.

**Comment by Screeen** [comment]
Thank you for your reply.
I opened the issue because settings the number of filters to 256 as in the original publication gives inconsistent shapes. The network won't build because the input and output of the first Resblock will not have the same shape.
