### ISSUE TITLE
The device in order to implement this code

### ISSUE THREAD

**Issue by zyc-c** [JiuSenso/SELD-TCN#6]
Hello,Sir
Firstly,Thanks your sharing.I have some question for the system implementation.
Actually,I want to know which device was used to implement this code, CPU or GPU？I could implement this code on CPU.Considering lots of parameters,I want to achieve it on GPU,however ,I don't make it up to now.
[numpy.core._exceptions._ArrayMemoryError: Unable to allocate 128. MiB for an array with shape (8192, 2048) and data type float64]It's one of mistakes I met.
So ,if you make it on GPU ,could you share me your environment setting or other  essential elements to make it？
Thanks

**Comment by giusenso** [comment]
Sorry for the delay, I did not notice this issue. However, I would not have been useful to you anyway because I used a cpu.
