### ISSUE TITLE
Hello,How to resolve ov2 audio?

### ISSUE THREAD

**Issue by jzb1111** [JiuSenso/SELD-TCN#7]
Hi giusenso,
I implement your work with tensorflow,
and I get this problem
when I try algorithm on ov1 data,everything work well,but when I try ov2 data,the loss just can not go small,how to resolve this problem?

**Comment by giusenso** [comment]
Hi jzb1111,
I'll try to review the code as soon as possible (but to be honest I'm quite busy in this period). In the meanwhile, please let me know if you find a workaround or any other bug.

**Comment by jzb1111** [comment]
Thanks giusenso,
For the problem of multi-source localization, I tried DPLM and SELD TCN, and all my attempts have failed, both method are OK with ov1 audio, but can't work on ov2 audio
